/**
 * @copyright Georgia Institute of Technology, 2024
 * @file: octomap_to_gridmap.h
 * @author: ctaylor319@gatech.edu
 * @date: 09/12/2024
 * @brief: converts octomap message into a grid_map message, which is used
 * by motion_planning to create an SDF of the environment
 *
 */

#include <rclcpp/rclcpp.hpp>

class MapConversion : public rclcpp::Node
{
public:

    // Constructors & Destructors
    MapConversion();
    ~MapConversion();
    
private:
    
    // Publishers and subscribers
    rclcpp::Publisher<grid_map_msgs::msg::GridMap>::SharedPtr _gridmap_publisher;
    rclcpp::Subscription<octomap_msgs::msg::Octomap>::SharedPtr _octomap_subscriber;

    /**
     * @brief: callback function for when we receive an octomap message. Converts
     * and publishes as a grid_map message.
     *
     * @param msg [in]: octomap message containing full map of surrounding environment.
     * Generated by octomap_server2 package.
     */
    void octomapCallback(octomap_msgs::msg::Octomap msg) const;
};