/**
 * Georgia Institute of Technology, 2024
 * @file: SDF_generation.h
 * @author: ctaylor319@gatech.edu
 * @date: 09/12/2024
 * @brief: generates an SDF as an obstacle input to the motion planning
 * algorithm.
 *
 */

#include <rclcpp/rclcpp.hpp>
#include <grid_map_core/GridMap.hpp>
#include <grid_map_msgs/msg/grid_map.hpp>

class SDFGeneration : public rclcpp::Node
{
public:

    SDFGeneration();
    ~SDFGeneration();

private:
    
    rclcpp::Subscription<grid_map_msgs::msg::GridMap>::SharedPtr _gridmap_subscriber;
    rclcpp::Publisher<grid_map_msgs::msg::GridMap>::SharedPtr _sdf_publisher;

    /**
     * @brief: callback function for when we receive an octomap message. Converts
     * and publishes as a grid_map message.
     * @param msg [in]: octomap message containing full map of surrounding environment.
     * Generated by octomap_server2 package.
     */
    void gridMapCallback(grid_map_msgs::msg::GridMap msg) const;
};