<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="lidar">
    <xacro:property name="base_radius" value="0.01"/>
    <xacro:property name="base_height" value="0.01"/>
    <xacro:property name="lidar_radius" value="0.008"/>
    <xacro:property name="lidar_height" value="0.03"/>

    <gazebo reference="lidar_base">
        <material>Gazebo/Grey</material>
        <mu1>0.2</mu1>
        <mu2>0.2</mu2>
    </gazebo>

    <link name="lidar_base">
        <visual>
            <geometry>
                <cylinder length="${base_height}" radius="${base_radius}"/>
            </geometry>
        </visual>

        <collision>
            <geometry>
                <cylinder length="${base_height}" radius="${base_radius}"/>
            </geometry>
        </collision>

        <inertial>
            <mass value="0.1"/>
            <inertia ixx="${(1/12) * 0.1 * (3 * base_radius * base_radius + base_height * base_height)}" ixy="0" ixz="0" iyy="${(1/12) * 0.1 * (3 * base_radius * base_radius + base_height * base_height)}" iyz="0" izz="${(1/2) * 0.1 * base_radius * base_radius}"/>
        </inertial>
    </link>

    <gazebo reference="lidar_rot">
        <material>Gazebo/RedGlow</material>
        <mu1>0.2</mu1>
        <mu2>0.2</mu2>
    </gazebo>

    <link name="lidar_rot">
        <visual>
            <geometry>
            <cylinder length="${lidar_height}" radius="${lidar_radius}"/>
            </geometry>
        </visual>

        <collision>
            <geometry>
            <cylinder length="${lidar_height}" radius="${lidar_radius}"/>
            </geometry>
        </collision>

        <inertial>
            <mass value="0.1"/>
            <inertia ixx="${(1/12) * 0.1 * (3 * lidar_radius * lidar_radius + lidar_height * lidar_height)}" ixy="0" ixz="0" iyy="${(1/12) * 0.1 * (3 * lidar_radius * lidar_radius + lidar_height * lidar_height)}" iyz="0" izz="${(1/2) * 0.1 * lidar_radius * lidar_radius}"/>
        </inertial>
    </link>

    <joint name="lidarRot" type="continuous">
        <parent link="lidar_base"/>
        <child link="lidar_rot"/>
        <axis xyz="0 0 1"/>
        <origin xyz = "0 0 ${base_height/2}"/>
        <dynamics friction="0.1"/>
    </joint>
</robot>